#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
# Dwarf: A PICKit 2 GUI for Linux
# Modernized for Python 3 / GTK 3
#
# Original:
# Copyright (C) 2009 Nathan Dumont
#
# Modernization:
# Python 3 + PyGObject + GTK 3
#

import gi
gi.require_version("Gtk", "3.0")

from gi.repository import Gtk, Gdk
from subprocess import Popen, PIPE
import os
import sys
import getopt
import shutil


VERSION = "0.3-2026"

APP_FOLDER = os.path.dirname(os.path.abspath(__file__))

# Command used to communicate with the PICkit 2
PK2CMD = "pk2cmd"


class MainWindow(Gtk.Window):
    """Main Dwarf window."""

    def __init__(self, verbosity=False):
        super().__init__(title=f"Dwarf {VERSION}")

        self.verbosity = verbosity

        self.set_border_width(10)
        self.set_default_size(700, 200)

        self.connect("destroy", self.destroy_cb)

        # Track application readiness
        self.ready = {
            "file": False,
            "device": False
        }

        self.source_file = ""
        self.programmer_name = ""
        self.updating_power_switch = False

        # ---------------------------------------------------------
        # Main layout
        # ---------------------------------------------------------

        self.layout = Gtk.Box(
            orientation=Gtk.Orientation.VERTICAL,
            spacing=10
        )

        # ROW 1: File selection & Programmer / Device Info
        self.row1_layout = Gtk.Box(
            orientation=Gtk.Orientation.HORIZONTAL,
            spacing=10
        )

        # ROW 2: Voltage & Target Power controls
        self.row2_layout = Gtk.Box(
            orientation=Gtk.Orientation.HORIZONTAL,
            spacing=10
        )

        # ROW 3: Actions
        self.row3_layout = Gtk.Box(
            orientation=Gtk.Orientation.HORIZONTAL,
            spacing=5
        )

        # ROW 4: Status Bar
        self.status_layout = Gtk.Box(
            orientation=Gtk.Orientation.HORIZONTAL,
            spacing=5
        )

        # ---------------------------------------------------------
        # Row 1 Components
        # ---------------------------------------------------------

        # Open HEX button
        self.open_btn = Gtk.Button.new_from_icon_name(
            "document-open",
            Gtk.IconSize.BUTTON
        )
        self.open_btn.set_tooltip_text("Open HEX file")
        self.open_btn.connect("clicked", self.open_cb)
        self.row1_layout.pack_start(self.open_btn, False, False, 0)

        # Selected HEX File label
        self.file_label = Gtk.Label(label="No file selected")
        self.file_label.set_ellipsize(3) # Ellipsize at end
        self.file_label_frame = Gtk.Frame(label="Selected HEX File")
        self.file_label_frame.add(self.file_label)
        self.row1_layout.pack_start(self.file_label_frame, True, True, 0)

        # Programmer label
        self.programmer_label = Gtk.Label(label="(none)")
        self.programmer_frame = Gtk.Frame(label="Programmer")
        self.programmer_frame.add(self.programmer_label)
        self.row1_layout.pack_start(self.programmer_frame, False, False, 0)

        # Device label
        self.model = Gtk.Label(label="(none)")
        self.model.set_size_request(120, -1)
        self.model_frame = Gtk.Frame(label="Target PIC")
        self.model_frame.add(self.model)
        self.row1_layout.pack_start(self.model_frame, False, False, 0)

        # Detect button
        self.auto_btn = self.make_image_button(
            "system-search",
            "Detect PICkit & PIC",
            self.auto_cb
        )
        self.row1_layout.pack_start(self.auto_btn, False, False, 0)

        # ---------------------------------------------------------
        # Row 2 Components: Voltage & Target Power Controls
        # ---------------------------------------------------------

        self.voltage_frame = Gtk.Frame(label="Target Voltage & Power (VDD)")
        voltage_inner = Gtk.Box(
            orientation=Gtk.Orientation.HORIZONTAL,
            spacing=15
        )
        voltage_inner.set_border_width(5)

        self.voltage_label = Gtk.Label(label="Voltage (V):")
        voltage_inner.pack_start(self.voltage_label, False, False, 0)

        # Adjustment: value, lower, upper, step_increment, page_increment, page_size
        adj = Gtk.Adjustment(value=5.0, lower=1.8, upper=5.0, step_increment=0.1, page_increment=1.0, page_size=0)
        self.voltage_spin = Gtk.SpinButton(adjustment=adj, climb_rate=0.1, digits=1)
        self.voltage_spin.set_numeric(True)
        self.voltage_spin.set_width_chars(5)
        voltage_inner.pack_start(self.voltage_spin, False, False, 0)

        self.power_label = Gtk.Label(label="Supply VDD:")
        voltage_inner.pack_start(self.power_label, False, False, 0)

        self.power_switch = Gtk.Switch()
        self.power_switch.set_active(False)
        self.power_switch.connect("notify::active", self.power_switch_cb)
        voltage_inner.pack_start(self.power_switch, False, False, 0)

        self.voltage_frame.add(voltage_inner)
        self.row2_layout.pack_start(self.voltage_frame, True, True, 0)

        # ---------------------------------------------------------
        # Row 3 Components: Action Buttons
        # ---------------------------------------------------------

        self.program_btn = self.make_image_button(
            "media-floppy",
            "Program PIC",
            self.program_cb
        )
        self.program_btn.set_sensitive(False)
        self.row3_layout.pack_start(self.program_btn, True, True, 0)

        self.verify_btn = self.make_image_button(
            "checkbox-checked",
            "Verify PIC memory",
            self.verify_cb
        )
        self.verify_btn.set_sensitive(False)
        self.row3_layout.pack_start(self.verify_btn, True, True, 0)

        self.read_btn = self.make_image_button(
            "document-save",
            "Read PIC memory",
            self.read_cb
        )
        self.read_btn.set_sensitive(False)
        self.row3_layout.pack_start(self.read_btn, True, True, 0)

        self.erase_btn = self.make_image_button(
            "edit-clear",
            "Erase PIC memory",
            self.erase_cb
        )
        self.erase_btn.set_sensitive(False)
        self.row3_layout.pack_start(self.erase_btn, True, True, 0)

        self.blank_btn = self.make_image_button(
            "dialog-information",
            "Blank Check PIC",
            self.blank_cb
        )
        self.blank_btn.set_sensitive(False)
        self.row3_layout.pack_start(self.blank_btn, True, True, 0)

        self.run_btn = self.make_image_button(
            "media-playback-start",
            "Run PIC",
            self.run_cb
        )
        self.run_btn.set_sensitive(False)
        self.row3_layout.pack_start(self.run_btn, True, True, 0)

        self.stop_btn = self.make_image_button(
            "media-playback-stop",
            "Stop PIC",
            self.stop_cb
        )
        self.stop_btn.set_sensitive(False)
        self.row3_layout.pack_start(self.stop_btn, True, True, 0)

        self.exit_btn = Gtk.Button.new_from_icon_name(
            "application-exit",
            Gtk.IconSize.BUTTON
        )
        self.exit_btn.set_tooltip_text("Exit")
        self.exit_btn.connect("clicked", self.destroy_cb)
        self.row3_layout.pack_start(self.exit_btn, False, False, 0)

        # ---------------------------------------------------------
        # Row 4 Components: Status
        # ---------------------------------------------------------

        self.status_label = Gtk.Label(label="Status: OK")
        self.status_label.set_xalign(0)
        self.status_layout.pack_start(self.status_label, True, True, 5)

        self.status_btn = Gtk.Button(label="Details")
        self.status_btn.set_sensitive(False)
        self.status_btn.connect("clicked", self.status_popup_cb)
        self.status_layout.pack_start(self.status_btn, False, False, 0)

        # ---------------------------------------------------------
        # Add layouts to main Window
        # ---------------------------------------------------------

        self.layout.pack_start(self.row1_layout, False, False, 0)
        self.layout.pack_start(self.row2_layout, False, False, 0)
        self.layout.pack_start(self.row3_layout, False, False, 0)
        self.layout.pack_start(self.status_layout, False, False, 0)

        self.add(self.layout)

        # ---------------------------------------------------------
        # PICkit object
        # ---------------------------------------------------------

        self.prog = PicKit(
            self,
            self.verbosity
        )

        self.show_all()

        # Try to connect automatically
        self.prog.connect()

    def make_image_button(self, icon_name, tooltip, callback):
        button = Gtk.Button.new_from_icon_name(
            icon_name,
            Gtk.IconSize.BUTTON
        )
        button.set_tooltip_text(tooltip)
        button.connect("clicked", callback)
        return button

    def destroy_cb(self, *args):
        Gtk.main_quit()

    def auto_cb(self, *args):
        self.prog.connect()

    def open_cb(self, *args):
        dialog = Gtk.FileChooserDialog(
            title="Open HEX file",
            parent=self,
            action=Gtk.FileChooserAction.OPEN
        )

        dialog.add_buttons(
            Gtk.STOCK_CANCEL,
            Gtk.ResponseType.CANCEL,
            Gtk.STOCK_OPEN,
            Gtk.ResponseType.ACCEPT
        )

        hex_filter = Gtk.FileFilter()
        hex_filter.set_name("HEX files")
        hex_filter.add_pattern("*.hex")
        hex_filter.add_pattern("*.HEX")
        dialog.add_filter(hex_filter)

        all_filter = Gtk.FileFilter()
        all_filter.set_name("All files")
        all_filter.add_pattern("*")
        dialog.add_filter(all_filter)

        if self.source_file:
            folder = os.path.dirname(self.source_file)
            if os.path.isdir(folder):
                dialog.set_current_folder(folder)
        else:
            dialog.set_current_folder(os.path.expanduser("~"))

        response = dialog.run()

        if response == Gtk.ResponseType.ACCEPT:
            filename = dialog.get_filename()
            if filename:
                self.set_file(filename)

        dialog.destroy()

    def set_file(self, filename):
        if not os.path.isfile(filename):
            self.status(
                "HEX file not found",
                filename,
                "red"
            )
            return

        self.source_file = os.path.abspath(filename)
        self.ready["file"] = True

        basename = os.path.basename(self.source_file)
        self.file_label.set_text(basename)
        self.file_label.set_tooltip_text(self.source_file)

        self.set_title(f"Dwarf {VERSION}: {basename}")

        self.status(
            f"HEX selected: {basename}",
            self.source_file,
            "green"
        )

        self.update_active("file", True)

        if self.verbosity:
            print(f"File chosen: {self.source_file}")

    def program_cb(self, *args):
        if not self.source_file:
            self.status("No HEX file selected", "", "red")
            return

        if not os.path.isfile(self.source_file):
            self.status("HEX file not found", self.source_file, "red")
            self.update_active("file", False)
            return

        self.prog.program(self.source_file)

    def verify_cb(self, *args):
        if not self.source_file:
            self.status("No HEX file selected", "", "red")
            return

        if not os.path.isfile(self.source_file):
            self.status("HEX file not found", self.source_file, "red")
            self.update_active("file", False)
            return

        self.prog.verify(self.source_file)

    def read_cb(self, *args):
        dialog = Gtk.FileChooserDialog(
            title="Save HEX dump to...",
            parent=self,
            action=Gtk.FileChooserAction.SAVE
        )

        dialog.add_buttons(
            Gtk.STOCK_CANCEL,
            Gtk.ResponseType.CANCEL,
            Gtk.STOCK_SAVE,
            Gtk.ResponseType.ACCEPT
        )

        dialog.set_do_overwrite_confirmation(True)

        response = dialog.run()

        if response == Gtk.ResponseType.ACCEPT:
            filename = dialog.get_filename()
            if filename:
                self.prog.read_device(filename)

        dialog.destroy()

    def erase_cb(self, *args):
        self.prog.erase()

    def blank_cb(self, *args):
        self.prog.blank_check()

    def run_cb(self, *args):
        self.prog.run()

    def stop_cb(self, *args):
        self.prog.stop()

    def get_voltage(self):
        return f"{self.voltage_spin.get_value():.1f}"

    def is_target_power_on(self):
        return self.power_switch.get_active()

    def power_switch_cb(self, switch, gparamspec):
        if self.updating_power_switch:
            return
        is_active = switch.get_active()
        self.prog.set_target_power(is_active)

    def status_popup_cb(self, *args):
        popup = StatusPopup(self.status_msg)
        popup.show_all()

    def status(self, msg, details="", colour="green"):
        self.status_label.set_text("Status: " + msg)
        self.status_msg = details

        colors = {
            "red": "#ffcccc",
            "green": "#ccffcc",
            "yellow": "#ffffcc"
        }

        css = Gtk.CssProvider()
        css_data = f"""
        label {{
            background-color: {colors.get(colour, "#ffffff")};
            padding: 5px;
        }}
        """

        css.load_from_data(css_data.encode())
        self.status_label.get_style_context().add_provider(
            css,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
        )

        self.status_btn.set_sensitive(bool(details))

    def update_active(self, reason, value):
        self.ready[reason] = value

        device_ready = self.ready["device"]
        file_ready = self.ready["file"]

        self.program_btn.set_sensitive(device_ready and file_ready)
        self.verify_btn.set_sensitive(device_ready and file_ready)
        self.read_btn.set_sensitive(device_ready)
        self.erase_btn.set_sensitive(device_ready)
        self.blank_btn.set_sensitive(device_ready)
        self.run_btn.set_sensitive(device_ready)
        self.stop_btn.set_sensitive(device_ready)


class StatusPopup(Gtk.Window):

    def __init__(self, message):
        super().__init__(title="Dwarf: Status Messages")

        self.set_border_width(10)
        self.set_default_size(500, 250)

        layout = Gtk.Box(
            orientation=Gtk.Orientation.VERTICAL,
            spacing=10
        )

        text_view = Gtk.TextView()
        text_view.set_editable(False)
        text_view.set_cursor_visible(False)
        text_view.set_wrap_mode(Gtk.WrapMode.WORD)

        buffer = text_view.get_buffer()
        buffer.set_text(message or "(no details)")

        scroll = Gtk.ScrolledWindow()
        scroll.set_policy(
            Gtk.PolicyType.AUTOMATIC,
            Gtk.PolicyType.AUTOMATIC
        )
        scroll.add(text_view)

        layout.pack_start(scroll, True, True, 0)

        close_btn = Gtk.Button(label="Close")
        close_btn.connect("clicked", lambda *_: self.destroy())

        layout.pack_end(close_btn, False, False, 0)
        self.add(layout)


class PicKit:

    def __init__(self, parent, verbosity=False):
        self.verbosity = verbosity
        self.cmd = PK2CMD
        self.parent = parent
        self.device = ""

    def detect_programmer(self):
        """Scans for connected PICkit programmers and returns the name/type."""
        if shutil.which(self.cmd) is None:
            return "No pk2cmd"

        output = self._run_command(["-S"])

        if "No PICkit" in output or "not found" in output:
            return None

        # Parse the programmer name
        for line in output.splitlines():
            if "Unit type:" in line:
                return line.split(":", 1)[1].strip()
            if "PICkit 3" in line:
                return "PICkit 3"
            if "PICkit 2" in line:
                return "PICkit 2"
            if "PKOB" in line:
                return "PKOB"

        if "Operation Succeeded" in output:
            return "PICkit (Detected)"

        return None

    def connect(self):
        if shutil.which(self.cmd) is None:
            self.device = ""
            self.parent.programmer_name = ""
            self.parent.programmer_label.set_text("(none)")
            self.parent.model.set_text("(none)")
            self.parent.status(
                "pk2cmd not installed!",
                f"Could not find '{self.cmd}' in PATH.",
                "red"
            )
            self.parent.update_active("device", False)
            self.show_error(
                "pk2cmd Required!",
                "The pk2cmd command line program could not be found.\n\n"
                "Install pk2cmd and make sure it is available in PATH."
            )
            return False

        prog_type = self.detect_programmer()
        if not prog_type:
            self.device = ""
            self.parent.programmer_name = ""
            self.parent.programmer_label.set_text("(none)")
            self.parent.model.set_text("(none)")
            self.parent.status(
                "Programmer not found",
                "Please connect a PICkit 2/3 or PKOB programmer.",
                "yellow"
            )
            self.parent.update_active("device", False)
            return False

        self.parent.programmer_name = prog_type
        self.parent.programmer_label.set_text(prog_type)

        opts = ["-P"]
        voltage_val = self.parent.get_voltage()
        if voltage_val:
            opts.append(f"-A{voltage_val}")

        if self.parent.is_target_power_on():
            opts.append("-T")

        output = self._run_command(opts)

        if "No PICkit" in output or "not found" in output:
            self.device = ""
            self.parent.model.set_text("(none)")
            self.parent.status(
                "Programmer error",
                output,
                "yellow"
            )
            self.parent.update_active("device", False)
            return False

        if "No known part found" in output or ("Device ID" in output and "not found" in output):
            self.device = ""
            self.parent.model.set_text("(none)")
            self.parent.status(
                "No PIC found",
                output + "\n\n(Ensure target board is powered or VDD is enabled)",
                "yellow"
            )
            self.parent.update_active("device", False)
            return False

        marker = "Found part "
        if marker in output:
            start = output.find(marker) + len(marker)
            end = output.find(".", start)
            if end == -1:
                device = output[start:].strip()
            else:
                device = output[start:end].strip()

            self.device = device
            self.parent.model.set_text(device)
            self.parent.status(
                f"Detected {device} ({prog_type})",
                output,
                "green"
            )
            self.parent.update_active("device", True)
            return True

        self.device = ""
        self.parent.model.set_text("(unknown)")
        self.parent.status(
            "Could not identify PIC",
            output,
            "yellow"
        )
        self.parent.update_active("device", False)
        return False

    def show_error(self, title, message):
        dialog = Gtk.MessageDialog(
            transient_for=self.parent,
            flags=Gtk.DialogFlags.MODAL,
            message_type=Gtk.MessageType.ERROR,
            buttons=Gtk.ButtonsType.CLOSE,
            text=title
        )
        dialog.format_secondary_text(message)
        dialog.run()
        dialog.destroy()

    def set_target_power(self, is_on):
        opts = []
        if self.device:
            opts.append("-P" + self.device)
            
        voltage_val = self.parent.get_voltage()
        if voltage_val:
            opts.append(f"-A{voltage_val}")
            
        if is_on:
            opts.append("-T")
            
        output = self._run_command(opts)
        
        if is_on:
            self.parent.status("Target power ON", output, "green")
        else:
            self.parent.status("Target power OFF", output, "green")

    def program(self, hexfile):
        if not self.device:
            self.parent.status("No PIC detected", "", "red")
            return

        opts = [
            "-P" + self.device,
            "-F" + hexfile,
            "-M"
        ]

        voltage_val = self.parent.get_voltage()
        if voltage_val:
            opts.append(f"-A{voltage_val}")
            
        if self.parent.is_target_power_on():
            opts.append("-T")

        output = self._run_command(opts)

        if "Program Succeeded" in output:
            self.parent.status("Program Succeeded", output, "green")
        else:
            self.parent.status("Program Failed", output, "red")

    def verify(self, hexfile):
        if not self.device:
            self.parent.status("No PIC detected", "", "red")
            return

        opts = [
            "-P" + self.device,
            "-F" + hexfile,
            "-Y"
        ]

        voltage_val = self.parent.get_voltage()
        if voltage_val:
            opts.append(f"-A{voltage_val}")
            
        if self.parent.is_target_power_on():
            opts.append("-T")

        output = self._run_command(opts)

        if "Verify Succeeded" in output or "Operation Succeeded" in output:
            self.parent.status("Verify Succeeded", output, "green")
        else:
            self.parent.status("Verify Failed", output, "red")

    def read_device(self, hexfile):
        if not self.device:
            self.parent.status("No PIC detected", "", "red")
            return

        opts = [
            "-P" + self.device,
            "-GF" + hexfile
        ]

        voltage_val = self.parent.get_voltage()
        if voltage_val:
            opts.append(f"-A{voltage_val}")
            
        if self.parent.is_target_power_on():
            opts.append("-T")

        output = self._run_command(opts)
        self.parent.status("PIC read complete", output, "green")

    def erase(self):
        if not self.device:
            self.parent.status("No PIC detected", "", "red")
            return

        opts = [
            "-P" + self.device,
            "-E"
        ]

        voltage_val = self.parent.get_voltage()
        if voltage_val:
            opts.append(f"-A{voltage_val}")
            
        if self.parent.is_target_power_on():
            opts.append("-T")

        output = self._run_command(opts)

        if "Erase Succeeded" in output or "Operation Succeeded" in output:
            self.parent.status("Erase Succeeded", output, "green")
        else:
            self.parent.status("Erase Failed", output, "red")

    def blank_check(self):
        if not self.device:
            self.parent.status("No PIC detected", "", "red")
            return

        opts = [
            "-P" + self.device,
            "-C"
        ]

        voltage_val = self.parent.get_voltage()
        if voltage_val:
            opts.append(f"-A{voltage_val}")
            
        if self.parent.is_target_power_on():
            opts.append("-T")

        output = self._run_command(opts)

        if "Device is Blank" in output or "Blank Check Succeeded" in output or "Operation Succeeded" in output:
            self.parent.status("Device is Blank", output, "green")
        else:
            self.parent.status("Device is NOT Blank", output, "red")

    def run(self):
        if not self.device:
            return

        opts = [
            "-P" + self.device,
            "-R",
            "-T"
        ]

        voltage_val = self.parent.get_voltage()
        if voltage_val:
            opts.append(f"-A{voltage_val}")

        output = self._run_command(opts)
        self.parent.status("PIC running", output, "green")
        
        # Sync switch to reflect that VDD is ON
        self.parent.updating_power_switch = True
        self.parent.power_switch.set_active(True)
        self.parent.updating_power_switch = False

    def stop(self):
        if not self.device:
            return

        opts = [
            "-P" + self.device
        ]

        voltage_val = self.parent.get_voltage()
        if voltage_val:
            opts.append(f"-A{voltage_val}")

        output = self._run_command(opts)
        self.parent.status("PIC stopped", output, "green")
        
        # Sync switch to reflect that VDD is OFF
        self.parent.updating_power_switch = True
        self.parent.power_switch.set_active(False)
        self.parent.updating_power_switch = False

    def _run_command(self, args):
        command = [self.cmd] + args

        if self.verbosity:
            print("$ " + " ".join(command))

        try:
            process = Popen(
                command,
                stdout=PIPE,
                stderr=PIPE,
                text=True
            )
            stdout, stderr = process.communicate()
            output = stdout
            if stderr:
                output += stderr

            if self.verbosity:
                print(output)

            return output

        except FileNotFoundError:
            return f"Error: {self.cmd} not found."
        except Exception as exc:
            return f"Error executing {self.cmd}: {exc}"


def usage():

    print(
        "dwarf [options] [filename]"
    )

    print()

    print(
        "Starts the Dwarf GUI application."
    )

    print(
        "The optional filename is a standard "
        "PIC HEX file."
    )

    print()

    print("Options")

    print(
        "  -v, --verbose   "
        "Print pk2cmd commands."
    )

    print(
        "  -h, --help      "
        "Show this help."
    )

    print()

    print(
        "Dwarf modernized for Python 3 / GTK 3."
    )


def main():

    try:

        optlist, args = getopt.gnu_getopt(
            sys.argv[1:],
            "vh",
            ["verbose", "help"]
        )

    except getopt.GetoptError as err:

        print(str(err))
        usage()
        sys.exit(2)

    verbosity = False

    for option, argument in optlist:

        if option in ("-h", "--help"):

            usage()
            sys.exit(0)

        elif option in ("-v", "--verbose"):

            verbosity = True

    main_win = MainWindow(
        verbosity
    )

    if len(args) >= 1:

        main_win.set_file(
            args[0]
        )

        if len(args) > 1:

            print(
                "Warning: can only select "
                "one file; first argument used."
            )

    Gtk.main()


if __name__ == "__main__":
    main()
