#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
# Dwarf: A PICKit 2 GUI for Linux
# Modernized for Python 3 / GTK 3
#
# Original:
# Copyright (C) 2009 Nathan Dumont
#
# Modernization:
# Python 3 + PyGObject + GTK 3
#

import gi
gi.require_version("Gtk", "3.0")

from gi.repository import Gtk, Gdk
from subprocess import Popen, PIPE
import os
import sys
import getopt
import shutil


VERSION = "0.3-2026"

APP_FOLDER = os.path.dirname(os.path.abspath(__file__))

# Command used to communicate with the PICkit 2
PK2CMD = "pk2cmd"


class MainWindow(Gtk.Window):
    """Main Dwarf window."""

    def __init__(self, verbosity=False):
        super().__init__(title=f"Dwarf {VERSION}")

        self.verbosity = verbosity

        self.set_border_width(5)
        self.set_default_size(650, 120)

        self.connect("destroy", self.destroy_cb)

        # Track application readiness
        self.ready = {
            "file": False,
            "device": False
        }

        self.source_file = ""

        # ---------------------------------------------------------
        # Main layout
        # ---------------------------------------------------------

        self.layout = Gtk.Box(
            orientation=Gtk.Orientation.VERTICAL,
            spacing=5
        )

        self.bar_layout = Gtk.Box(
            orientation=Gtk.Orientation.HORIZONTAL,
            spacing=5
        )

        self.button_layout = Gtk.Box(
            orientation=Gtk.Orientation.HORIZONTAL,
            spacing=2
        )

        # ---------------------------------------------------------
        # Open HEX button
        # ---------------------------------------------------------

        self.open_btn = Gtk.Button.new_from_icon_name(
            "document-open",
            Gtk.IconSize.BUTTON
        )

        self.open_btn.set_tooltip_text("Open HEX file")
        self.open_btn.connect("clicked", self.open_cb)

        self.bar_layout.pack_start(
            self.open_btn,
            False,
            False,
            0
        )

        # ---------------------------------------------------------
        # Device label
        # ---------------------------------------------------------

        self.model = Gtk.Label(label="(none)")
        self.model.set_size_request(120, -1)

        self.model_frame = Gtk.Frame()
        self.model_frame.add(self.model)

        self.bar_layout.pack_start(
            self.model_frame,
            False,
            False,
            0
        )

        # ---------------------------------------------------------
        # Auto detect
        # ---------------------------------------------------------

        self.auto_btn = self.make_image_button(
            "system-search",
            "Detect PICkit 2",
            self.auto_cb
        )

        self.button_layout.pack_start(
            self.auto_btn,
            False,
            False,
            0
        )

        # ---------------------------------------------------------
        # Program
        # ---------------------------------------------------------

        self.program_btn = self.make_image_button(
            "media-floppy",
            "Program PIC",
            self.program_cb
        )

        self.program_btn.set_sensitive(False)

        self.button_layout.pack_start(
            self.program_btn,
            False,
            False,
            0
        )

        # ---------------------------------------------------------
        # Read
        # ---------------------------------------------------------

        self.read_btn = self.make_image_button(
            "document-save",
            "Read PIC",
            self.read_cb
        )

        self.read_btn.set_sensitive(False)

        self.button_layout.pack_start(
            self.read_btn,
            False,
            False,
            0
        )

        # ---------------------------------------------------------
        # Run
        # ---------------------------------------------------------

        self.run_btn = self.make_image_button(
            "media-playback-start",
            "Run PIC",
            self.run_cb
        )

        self.run_btn.set_sensitive(False)

        self.button_layout.pack_start(
            self.run_btn,
            False,
            False,
            0
        )

        # ---------------------------------------------------------
        # Stop
        # ---------------------------------------------------------

        self.stop_btn = self.make_image_button(
            "media-playback-stop",
            "Stop PIC",
            self.stop_cb
        )

        self.stop_btn.set_sensitive(False)

        self.button_layout.pack_start(
            self.stop_btn,
            False,
            False,
            0
        )

        # ---------------------------------------------------------
        # Exit
        # ---------------------------------------------------------

        self.exit_btn = Gtk.Button.new_from_icon_name(
            "application-exit",
            Gtk.IconSize.BUTTON
        )

        self.exit_btn.set_tooltip_text("Exit")
        self.exit_btn.connect("clicked", self.destroy_cb)

        self.button_layout.pack_start(
            self.exit_btn,
            False,
            False,
            0
        )

        self.bar_layout.pack_end(
            self.button_layout,
            False,
            False,
            0
        )

        self.layout.pack_start(
            self.bar_layout,
            False,
            False,
            0
        )

        # ---------------------------------------------------------
        # Status
        # ---------------------------------------------------------

        self.status_layout = Gtk.Box(
            orientation=Gtk.Orientation.HORIZONTAL,
            spacing=5
        )

        self.status_label = Gtk.Label(label="Status: OK")
        self.status_label.set_xalign(0)

        self.status_layout.pack_start(
            self.status_label,
            True,
            True,
            5
        )

        self.status_btn = Gtk.Button(label="Details")
        self.status_btn.set_sensitive(False)
        self.status_btn.connect(
            "clicked",
            self.status_popup_cb
        )

        self.status_layout.pack_start(
            self.status_btn,
            False,
            False,
            0
        )

        self.layout.pack_start(
            self.status_layout,
            False,
            False,
            0
        )

        self.add(self.layout)

        # ---------------------------------------------------------
        # PICkit object
        # ---------------------------------------------------------

        self.prog = PicKit(
            self,
            self.verbosity
        )

        self.show_all()

        # Try to connect automatically
        self.prog.connect()

    # -------------------------------------------------------------
    # GUI helpers
    # -------------------------------------------------------------

    def make_image_button(self, icon_name, tooltip, callback):
        button = Gtk.Button.new_from_icon_name(
            icon_name,
            Gtk.IconSize.BUTTON
        )

        button.set_tooltip_text(tooltip)
        button.connect("clicked", callback)

        return button

    def destroy_cb(self, *args):
        Gtk.main_quit()

    # -------------------------------------------------------------
    # PICkit callbacks
    # -------------------------------------------------------------

    def auto_cb(self, *args):
        self.prog.connect()

    # -------------------------------------------------------------
    # File selection
    # -------------------------------------------------------------

    def open_cb(self, *args):

        dialog = Gtk.FileChooserDialog(
            title="Open HEX file",
            parent=self,
            action=Gtk.FileChooserAction.OPEN
        )

        dialog.add_buttons(
            Gtk.STOCK_CANCEL,
            Gtk.ResponseType.CANCEL,
            Gtk.STOCK_OPEN,
            Gtk.ResponseType.ACCEPT
        )

        # HEX filter
        hex_filter = Gtk.FileFilter()
        hex_filter.set_name("HEX files")
        hex_filter.add_pattern("*.hex")
        hex_filter.add_pattern("*.HEX")

        dialog.add_filter(hex_filter)

        # All files
        all_filter = Gtk.FileFilter()
        all_filter.set_name("All files")
        all_filter.add_pattern("*")

        dialog.add_filter(all_filter)

        if self.source_file:
            folder = os.path.dirname(self.source_file)

            if os.path.isdir(folder):
                dialog.set_current_folder(folder)
        else:
            dialog.set_current_folder(
                os.path.expanduser("~")
            )

        response = dialog.run()

        if response == Gtk.ResponseType.ACCEPT:

            filename = dialog.get_filename()

            if filename:
                self.set_file(filename)

        dialog.destroy()

    def set_file(self, filename):

        if not os.path.isfile(filename):
            self.status(
                "HEX file not found",
                filename,
                "red"
            )
            return

        self.source_file = os.path.abspath(filename)

        self.ready["file"] = True

        basename = os.path.basename(
            self.source_file
        )

        self.set_title(
            f"Dwarf {VERSION}: {basename}"
        )

        self.status(
            f"HEX selected: {basename}",
            self.source_file,
            "green"
        )

        self.update_active(
            "file",
            True
        )

        if self.verbosity:
            print(
                f"File chosen: {self.source_file}"
            )

    # -------------------------------------------------------------
    # Program
    # -------------------------------------------------------------

    def program_cb(self, *args):

        if not self.source_file:
            self.status(
                "No HEX file selected",
                "",
                "red"
            )
            return

        if not os.path.isfile(self.source_file):
            self.status(
                "HEX file not found",
                self.source_file,
                "red"
            )

            self.update_active(
                "file",
                False
            )

            return

        self.prog.program(
            self.source_file
        )

    # -------------------------------------------------------------
    # Read PIC
    # -------------------------------------------------------------

    def read_cb(self, *args):

        dialog = Gtk.FileChooserDialog(
            title="Save HEX dump to...",
            parent=self,
            action=Gtk.FileChooserAction.SAVE
        )

        dialog.add_buttons(
            Gtk.STOCK_CANCEL,
            Gtk.ResponseType.CANCEL,
            Gtk.STOCK_SAVE,
            Gtk.ResponseType.ACCEPT
        )

        dialog.set_do_overwrite_confirmation(True)

        response = dialog.run()

        if response == Gtk.ResponseType.ACCEPT:

            filename = dialog.get_filename()

            if filename:
                self.prog.read_device(
                    filename
                )

        dialog.destroy()

    # -------------------------------------------------------------
    # Run PIC
    # -------------------------------------------------------------

    def run_cb(self, *args):
        self.prog.run()

    # -------------------------------------------------------------
    # Stop PIC
    # -------------------------------------------------------------

    def stop_cb(self, *args):
        self.prog.stop()

    # -------------------------------------------------------------
    # Status popup
    # -------------------------------------------------------------

    def status_popup_cb(self, *args):

        popup = StatusPopup(
            self.status_msg
        )

        popup.show_all()

    # -------------------------------------------------------------
    # Status handling
    # -------------------------------------------------------------

    def status(self, msg, details="", colour="green"):

        self.status_label.set_text(
            "Status: " + msg
        )

        self.status_msg = details

        colors = {
            "red": "#ffcccc",
            "green": "#ccffcc",
            "yellow": "#ffffcc"
        }

        css = Gtk.CssProvider()

        css_data = f"""
        label {{
            background-color: {colors.get(colour, "#ffffff")};
            padding: 5px;
        }}
        """

        css.load_from_data(
            css_data.encode()
        )

        self.status_label.get_style_context().add_provider(
            css,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
        )

        self.status_btn.set_sensitive(
            bool(details)
        )

    def update_active(self, reason, value):

        self.ready[reason] = value

        device_ready = self.ready["device"]
        file_ready = self.ready["file"]

        self.program_btn.set_sensitive(
            device_ready and file_ready
        )

        self.read_btn.set_sensitive(
            device_ready
        )

        self.run_btn.set_sensitive(
            device_ready
        )

        self.stop_btn.set_sensitive(
            device_ready
        )


class StatusPopup(Gtk.Window):

    def __init__(self, message):

        super().__init__(
            title="Dwarf: Status Messages"
        )

        self.set_border_width(10)
        self.set_default_size(500, 250)

        layout = Gtk.Box(
            orientation=Gtk.Orientation.VERTICAL,
            spacing=10
        )

        text_view = Gtk.TextView()

        text_view.set_editable(False)
        text_view.set_cursor_visible(False)
        text_view.set_wrap_mode(
            Gtk.WrapMode.WORD
        )

        buffer = text_view.get_buffer()

        buffer.set_text(
            message or "(no details)"
        )

        scroll = Gtk.ScrolledWindow()

        scroll.set_policy(
            Gtk.PolicyType.AUTOMATIC,
            Gtk.PolicyType.AUTOMATIC
        )

        scroll.add(text_view)

        layout.pack_start(
            scroll,
            True,
            True,
            0
        )

        close_btn = Gtk.Button(
            label="Close"
        )

        close_btn.connect(
            "clicked",
            lambda *_: self.destroy()
        )

        layout.pack_end(
            close_btn,
            False,
            False,
            0
        )

        self.add(layout)


class PicKit:

    def __init__(self, parent, verbosity=False):

        self.verbosity = verbosity
        self.cmd = PK2CMD
        self.parent = parent
        self.device = ""

    # -------------------------------------------------------------
    # Connect / detect
    # -------------------------------------------------------------

    def connect(self):

        # Check whether pk2cmd exists
        if shutil.which(self.cmd) is None:

            self.device = ""

            self.parent.model.set_text(
                "(none)"
            )

            self.parent.status(
                "pk2cmd not installed!",
                f"Could not find '{self.cmd}' in PATH.",
                "red"
            )

            self.parent.update_active(
                "device",
                False
            )

            self.show_error(
                "pk2cmd Required!",
                "The pk2cmd command line program "
                "could not be found.\n\n"
                "Install pk2cmd and make sure it is "
                "available in PATH."
            )

            return False

        output = self._run_command(
            ["-P"]
        )

        if "No PICkit 2 found." in output:

            self.device = ""

            self.parent.model.set_text(
                "(none)"
            )

            self.parent.status(
                "PICkit 2 not found",
                output,
                "yellow"
            )

            self.parent.update_active(
                "device",
                False
            )

            return False

        if "No known part found" in output:

            self.device = ""

            self.parent.model.set_text(
                "(none)"
            )

            self.parent.status(
                "No PIC found",
                output,
                "yellow"
            )

            self.parent.update_active(
                "device",
                False
            )

            return False

        # ---------------------------------------------------------
        # Parse detected PIC
        # ---------------------------------------------------------

        marker = "Found part "

        if marker in output:

            start = output.find(marker) + len(marker)

            end = output.find(
                ".",
                start
            )

            if end == -1:
                device = output[start:].strip()
            else:
                device = output[start:end].strip()

            self.device = device

            self.parent.model.set_text(
                device
            )

            self.parent.status(
                f"Detected {device}",
                output,
                "green"
            )

            self.parent.update_active(
                "device",
                True
            )

            return True

        # Unknown output
        self.device = ""

        self.parent.model.set_text(
            "(unknown)"
        )

        self.parent.status(
            "Could not identify PIC",
            output,
            "yellow"
        )

        self.parent.update_active(
            "device",
            False
        )

        return False

    # -------------------------------------------------------------
    # Error dialog
    # -------------------------------------------------------------

    def show_error(self, title, message):

        dialog = Gtk.MessageDialog(
            transient_for=self.parent,
            flags=Gtk.DialogFlags.MODAL,
            message_type=Gtk.MessageType.ERROR,
            buttons=Gtk.ButtonsType.CLOSE,
            text=title
        )

        dialog.format_secondary_text(
            message
        )

        dialog.run()
        dialog.destroy()

    # -------------------------------------------------------------
    # Program PIC
    # -------------------------------------------------------------

    def program(self, hexfile):

        if not self.device:
            self.parent.status(
                "No PIC detected",
                "",
                "red"
            )
            return

        opts = [
            "-P" + self.device,
            "-F" + hexfile,
            "-M"
        ]

        output = self._run_command(
            opts
        )

        if "Program Succeeded" in output:

            self.parent.status(
                "Program Succeeded",
                output,
                "green"
            )

        else:

            self.parent.status(
                "Program Failed",
                output,
                "red"
            )

    # -------------------------------------------------------------
    # Read PIC
    # -------------------------------------------------------------

    def read_device(self, hexfile):

        if not self.device:
            self.parent.status(
                "No PIC detected",
                "",
                "red"
            )
            return

        opts = [
            "-P" + self.device,
            "-GF" + hexfile
        ]

        output = self._run_command(
            opts
        )

        self.parent.status(
            "PIC read complete",
            output,
            "green"
        )

    # -------------------------------------------------------------
    # Run PIC
    # -------------------------------------------------------------

    def run(self):

        if not self.device:
            return

        opts = [
            "-P" + self.device,
            "-R",
            "-T"
        ]

        output = self._run_command(
            opts
        )

        self.parent.status(
            "PIC running",
            output,
            "green"
        )

    # -------------------------------------------------------------
    # Stop PIC
    # -------------------------------------------------------------

    def stop(self):

        if not self.device:
            return

        opts = [
            "-P" + self.device
        ]

        output = self._run_command(
            opts
        )

        self.parent.status(
            "PIC stopped",
            output,
            "green"
        )

    # -------------------------------------------------------------
    # Execute pk2cmd
    # -------------------------------------------------------------

    def _run_command(self, args):

        command = [
            self.cmd
        ] + args

        if self.verbosity:
            print(
                "$ " + " ".join(command)
            )

        try:

            process = Popen(
                command,
                stdout=PIPE,
                stderr=PIPE,
                text=True
            )

            stdout, stderr = process.communicate()

            output = stdout

            if stderr:
                output += stderr

            if self.verbosity:
                print(output)

            return output

        except FileNotFoundError:

            return (
                f"Error: {self.cmd} "
                "not found."
            )

        except Exception as exc:

            return (
                f"Error executing pk2cmd: "
                f"{exc}"
            )


def usage():

    print(
        "dwarf [options] [filename]"
    )

    print()

    print(
        "Starts the Dwarf GUI application."
    )

    print(
        "The optional filename is a standard "
        "PIC HEX file."
    )

    print()

    print("Options")

    print(
        "  -v, --verbose   "
        "Print pk2cmd commands."
    )

    print(
        "  -h, --help      "
        "Show this help."
    )

    print()

    print(
        "Dwarf modernized for Python 3 / GTK 3."
    )


def main():

    try:

        optlist, args = getopt.gnu_getopt(
            sys.argv[1:],
            "vh",
            ["verbose", "help"]
        )

    except getopt.GetoptError as err:

        print(str(err))
        usage()
        sys.exit(2)

    verbosity = False

    for option, argument in optlist:

        if option in ("-h", "--help"):

            usage()
            sys.exit(0)

        elif option in ("-v", "--verbose"):

            verbosity = True

    main_win = MainWindow(
        verbosity
    )

    if len(args) >= 1:

        main_win.set_file(
            args[0]
        )

        if len(args) > 1:

            print(
                "Warning: can only select "
                "one file; first argument used."
            )

    Gtk.main()


if __name__ == "__main__":
    main()
